Adding curl logic and localhost building.

diff --git a/.github/workflows/docker-image-manual.yml b/.github/workflows/docker-image-manual.yml
--- a/.github/workflows/docker-image-manual.yml
+++ b/.github/workflows/docker-image-manual.yml
@@ -22,11 +22,51 @@ jobs:
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
         
     - name: Build Docker Image Test
-      run: docker build . --file Dockerfile --tag gophermotorsports/team_homepage_test:teamHomepage-TEST-PROD
+      run: |
+        docker build . --file Dockerfile --tag gophermotorsports/team_homepage_test:teamHomepage-TEST-PROD
+        if docker run --rm curlimages/curl:7:80.0 --version
+        then
+          docker push gophermotorsports/team_homepage_test:teamHomepage-TEST-PROD
+        else
+          exit 1
+        fi
+          
       
-    - name: Docker Push to Test Dockerhub Repo
-      run: docker push gophermotorsports/team_homepage_test:teamHomepage-TEST-PROD
-
+#    - name: Docker Push to Test Dockerhub Repo
+#     run: docker push gophermotorsports/team_homepage_test:teamHomepage-TEST-PROD
+      
+      
+#    - name: Report Status Slack
+#   - uses: ravsamhq/notify-slack-action@v1
+#      if: always()
+#      with:
+#        status: ${{ job.status }}
+#        notification_title: '{workflow} has {status_message}'
+#        notify_when: 'failure'
+#        mention_users: 'U0160UUNH8S,U02DLJT9DSR'
+#        mention_users_when: 'failure,warnings'
+#      env:
+#        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+        
+    - name: Report Status Email
+      if: always()
+      uses: dawidd6/action-send-mail@v2
+      with:
+        # mail server settings
+        server_address: smtp.gmail.com
+        server_port: 465
+        # user credentials
+        username: ${{ secrets.EMAIL_USERNAME }}
+        password: ${{ secrets.EMAIL_PASSWORD }}
+        # email subject
+        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
+        # email body as text
+        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
+        # comma-separated string, send email to
+        to: johndoe@gmail.com,doejohn@gmail.com
+        # from email name
+        from: github
+        
 #    - name: Test if Site is Successfully Curl'd
 #      run: |
 #        if curl /URL/ works; then
